name: Close and Release Sonatype Staging Repositories

on:
  workflow_dispatch:

jobs:
  deployment:
    if: github.repository == 'eclipse-velocitas/vehicle-app-java-sdk'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Project
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Close and Release 'vss-processor-plugin'
        working-directory: vss-processor-plugin
        continue-on-error: true
        env:
          ORG_GPG_KEY_ID: ${{ secrets.GPG_SUBKEY_ID }}
          ORG_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        run: ../gradlew findSonatypeStagingRepository closeAndReleaseSonatypeStagingRepository

      - name: Close and Release 'vehicle-app-java-sdk'
        continue-on-error: true
        env:
          ORG_GPG_KEY_ID: ${{ secrets.GPG_SUBKEY_ID }}
          ORG_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        run: ./gradlew findSonatypeStagingRepository closeAndReleaseSonatypeStagingRepository
